main/urls.py
from django.urls import path
from main.views import *
from main.views import add_quotes_ajax
from . import views

app_name = 'main'

urlpatterns = [
    path('create-quotes-ajax/',add_quotes_ajax,name="add_quotes_ajax"),
    path('filter-inggris/',filter_bahasa_inggris,name='filter_inggris'),
    path('filter-karya/',filter_buku_karya,name='filter_karya'),
    path('filter-empat/',filter_bintang_empat,name='filter_empat'),
    path('my-quotes/',show_my_quotes,name='show_my_quotes'),
    path('koleksi-buku/',show_semua, name ='show_semua'),
    path('login', login_user, name='login'),
    path('', show_main, name='show_main'),
    path('create-buku', create_buku, name='create_buku'),
    path('xml/', show_xml, name='show_xml'), 
    path('buku-json/', show_buku_json, name='show_buku_json'),
    path('bukukreasi-json/', show_buku_kreasi_json, name='show_bukukreasi_json'),
    path('myquotes-json/', show_my_quotes_json, name='show_myquotes_json'),
    path('profile-json/', show_profile_json, name='show_profile_json'), 
    path('quotes-json/', show_quotes_json, name='show_quotes_json'),
    path('level-json/', show_level_json, name='show_level_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('edit-buku/<int:id>', edit_buku, name='edit_buku'),
    path('delete/<int:id>', delete_buku, name='delete_buku'),
    path('preview/<int:id>', show_preview, name='show_preview'),
    path('preview-kreasi/<int:id>', show_preview_kreasi, name='show_preview_kreasi'),
    path('get-quotes-jason',get_quotes_json,name="get_quotes_json"),
    path('delete-quotes/<int:id>', delete_quotes, name='delete_quotes'),
    path("create-isi-buku", views.createIsiBuku, name="create_isi_buku"),
    path("create-isi-buku-baru", views.createIsiBuku, name="create_isi_buku_baru"),
    path("publish/<int:id_buku>", views.publish, name="publish"),
    path("create-isi-buku-saved/<int:id_buku>", views.autoSave, name="autoSave"),
    path("create-buku-baru", views.create_buku_baru, name='create_buku_baru'),
]

modul_favorites/urls.py
from django.urls import path
from modul_favorites.views import *

app_name = 'modul_favorites'

urlpatterns = [
    path('show_favorites/', show_favorites, name='show_favorites'),
    path('add_favorites/<int:id>', add_favorites, name='add_favorites'),
    path('remove_favorites/<int:id>', remove_favorites, name='remove_favorites'),
]

modul_preview/urls.py
from django.urls import path
from modul_preview.views import show_bacaan, show_bacaan_kreasi

app_name = 'modul_preview'

urlpatterns = [
    path('baca/<int:id>', show_bacaan, name='show_bacaan'),
    path('baca-kreasi/<int:id>', show_bacaan_kreasi, name='show_bacaan_kreasi'),
]

storica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('preview/', include('modul_preview.urls')),
    path('preview/baca/', include('modul_baca.urls')),
    path('favorites/', include('modul_favorites.urls')),
    path('create-buku/create-buku', include('modul_create_book.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

modul_preview/models.py
from django.db import models

# Create your models here.

modul_preview/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.models import Buku, BukuKreasi
from main.forms import BukuForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse


@login_required(login_url='/login')
def show_bacaan(request, id):
    buku = Buku.objects.get(pk = id)
    context = {
        'buku': buku,
    }
    return render(request, "bacaan.html", context)


@login_required(login_url='/login')
def show_bacaan_kreasi(request, id):
    karya = BukuKreasi.objects.get(pk = id)
    context = {
        'karya': karya,
    }
    return render(request, "bacaan_kreasi.html", context)

modul_preview/templates/preview_biasa.html
{% extends 'base.html' %}

{% block meta %}
<title>Preview</title>
{% endblock meta %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ buku.gambar }}" alt="{{ buku.judul }}" class="img-fluid card-img-top">
        </div>
        <div class="col-md-6">
            <h2>{{ buku.judul }}</h2>
            <p>{{ buku.description }}</p>
            <a href="{% url 'modul_preview:show_bacaan' buku.pk %}" class="btn btn-primary">
                Baca Buku
            </a>
            <a href="{% url 'modul_favorites:add_favorites' buku.pk %}" class="btn btn-primary">
                Tambahkan ke Favorit
            </a>
            <a href="{% url 'main:show_main'%}" class="btn btn-primary">
                Back to Home
            </a>
            <a href="{% url 'main:delete_buku' buku.pk%}" class="btn btn-danger">
                Delete
            </a>
        </div>
    </div>
</div>
{% endblock content %}

modul_preview/templates/preview_kreasi.html
{% extends 'base.html' %}

{% block meta %}
<title>Preview</title>
{% endblock meta %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ karya.gambar }}" alt="{{ karya.judul }}" class="img-fluid card-img-top">
        </div>
        <div class="col-md-6">
            <h2>{{ karya.judul }}</h2>
            <p>{{ karya.description }}</p>
            <a href="{% url 'modul_preview:show_bacaan_kreasi' karya.pk %}" class="btn btn-primary">
                Baca Buku
            </a>
            <a href="{% url 'main:show_main'%}" class="btn btn-primary">
                Back to Home
            </a>
            <a href="{% url 'main:delete_buku' karya.pk%}" class="btn btn-danger">
                Delete
            </a>
        </div>
    </div>
</div>
{% endblock content %}