main/urls.py
from django.urls import path
from main.views import *
from main.views import add_quotes_ajax
from . import views

app_name = 'main'

urlpatterns = [
    path('create-quotes-ajax/',add_quotes_ajax,name="add_quotes_ajax"),
    path('filter-inggris/',filter_bahasa_inggris,name='filter_inggris'),
    path('filter-karya/',filter_buku_karya,name='filter_karya'),
    path('filter-empat/',filter_bintang_empat,name='filter_empat'),
    path('my-quotes/',show_my_quotes,name='show_my_quotes'),
    path('koleksi-buku/',show_semua, name ='show_semua'),
    path('login', login_user, name='login'),
    path('', show_main, name='show_main'),
    path('create-buku', create_buku, name='create_buku'),
    path('xml/', show_xml, name='show_xml'), 
    path('buku-json/', show_buku_json, name='show_buku_json'),
    path('bukukreasi-json/', show_buku_kreasi_json, name='show_bukukreasi_json'),
    path('myquotes-json/', show_my_quotes_json, name='show_myquotes_json'),
    path('profile-json/', show_profile_json, name='show_profile_json'), 
    path('quotes-json/', show_quotes_json, name='show_quotes_json'),
    path('level-json/', show_level_json, name='show_level_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('edit-buku/<int:id>', edit_buku, name='edit_buku'),
    path('delete/<int:id>', delete_buku, name='delete_buku'),
    path('preview/<int:id>', show_preview, name='show_preview'),
    path('preview-kreasi/<int:id>', show_preview_kreasi, name='show_preview_kreasi'),
    path('get-quotes-jason',get_quotes_json,name="get_quotes_json"),
    path('delete-quotes/<int:id>', delete_quotes, name='delete_quotes'),
    path("create-isi-buku", views.createIsiBuku, name="create_isi_buku"),
    path("create-isi-buku-baru", views.createIsiBuku, name="create_isi_buku_baru"),
    path("publish/<int:id_buku>", views.publish, name="publish"),
    path("create-isi-buku-saved/<int:id_buku>", views.autoSave, name="autoSave"),
    path("create-buku-baru", views.create_buku_baru, name='create_buku_baru'),
]

modul_create_book/urls.py
from django.urls import path
from main.views import (
    show_main,
    create_buku,
    show_xml,
    show_buku_json,
    show_xml_by_id,
    show_json_by_id,
)
from main.views import register  # sesuaikan dengan nama fungsi yang dibuat
from main.views import login_user
from main.views import logout_user
from main.views import edit_buku
from main.views import delete_buku
from . import views

app_name = "main"

urlpatterns = [
    path("", show_main, name="show_main"),
    path("create-buku", create_buku, name="create_buku"),
    path("create-isi-buku", views.createIsiBuku, name="create_isi_buku"),
    path("create-isi-buku-baru", views.createIsiBuku, name="create_isi_buku_baru"),
    path("publish/<int:id_buku>", views.publish, name="publish"),
    path("create-isi-buku-saved/<int:id_buku>", views.autoSave, name="autoSave"),
    path("xml/", show_xml, name="show_xml"),
    path("json/", show_buku_json, name="show_json"),
    path("xml/<int:id>/", show_xml_by_id, name="show_xml_by_id"),
    path("json/<int:id>/", show_json_by_id, name="show_json_by_id"),
    path("register/", register, name="register"),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path("edit-buku/<int:id>", edit_buku, name="edit_buku"),
    path("delete/<int:id>", delete_buku, name="delete_buku"),
]

storica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('preview/', include('modul_preview.urls')),
    path('preview/baca/', include('modul_baca.urls')),
    path('favorites/', include('modul_favorites.urls')),
    path('create-buku/create-buku', include('modul_create_book.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Buku(models.Model):
    judul = models.CharField(max_length=255, null=True, blank=True)
    jumlah_halaman = models.PositiveIntegerField(null=True, blank=True)
    bahasa = models.CharField(max_length=50, null=True, blank=True)
    penulis = models.CharField(max_length=255, null=True, blank=True)
    penerbit = models.CharField(max_length=255, null=True, blank=True)
    jumlah_review = models.PositiveIntegerField(null=True, blank=True)
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    gambar = models.URLField(null=True, blank=True)
    tanggal_terbit = models.DateField(null=True, blank=True)
    buku_favorites = models.ManyToManyField(User)
    isi_buku = models.TextField(default="Sayangnya buku ini belum tersedia :(, silahkan coba buku lainnya")


class BukuKreasi(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    judul = models.CharField(max_length=255, null=True, blank=True)
    jumlah_halaman = models.PositiveIntegerField(null=True, blank=True)
    bahasa = models.CharField(max_length=50, null=True, blank=True)
    penulis = models.CharField(max_length=255, null=True, blank=True)
    penerbit = models.CharField(max_length=255, null=True, blank=True)
    jumlah_review = models.PositiveIntegerField(null=True, blank=True)
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    gambar = models.URLField(null=True, blank=True)
    tanggal_terbit = models.DateField(null=True, blank=True)
    is_published = models.BooleanField()
    isi_buku = models.TextField(null="",blank="")


    # Representasi teks model 
    def __str__(self):
        return self.judul

class level(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    level = models.PositiveIntegerField()
    buku_total = models.PositiveIntegerField()
    batas_atas = models.PositiveIntegerField()
    persen = models.PositiveIntegerField()


class quotes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    kata_kata = models.TextField()

class profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    gambar = models.URLField(null=True, blank=True)

main/forms.py
from django.forms import ModelForm
from main.models import BukuKreasi

class BukuForm(ModelForm):
    class Meta:
        model = BukuKreasi
        fields = ["judul", "jumlah_halaman", "bahasa", "penulis", "penerbit", "jumlah_review", "rating", "gambar", "tanggal_terbit", "isi_buku", "is_published"]

modul_create_book/forms.py
from django.forms import ModelForm
from main.models import Buku
from django import forms


class DateInput(forms.DateInput):
    input_type = "date"


class BukuForm(ModelForm):
    class Meta:
        model = Buku
        fields = [
            "id_buku",
            "judul",
            "jumlah_halaman",
            "bahasa",
            "penulis",
            "penerbit",
            "jumlah_review",
            "rating",
            "gambar",
            "tanggal_terbit",
            "isi_buku",
        ]

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.models import *
from main.forms import BukuForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from django.core.files.storage import FileSystemStorage
from django.core.exceptions import ObjectDoesNotExist


def get_buku_json(request):
    buku = Buku.objects.all().order_by("jumlah_review")
    return HttpResponse(serializers.serialize("json", buku))


def get_bukukreasi_json(request):
    bukukreasi = Buku.objects.all().order_by("jumlah_review")
    return HttpResponse(serializers.serialize("json", bukukreasi))


def show_semua(request):
    karya_pengguna = (
        BukuKreasi.objects.all().order_by("jumlah_review").filter(is_published=True)
    )
    bukus = Buku.objects.all().order_by("jumlah_review")

    context = {"bukus": bukus, "karya": karya_pengguna}
    return render(request, "semuabuku.html", context)


def show_main(request):
    karya_pengguna = (
        BukuKreasi.objects.all().order_by("jumlah_review").filter(is_published=True)
    )
    bukus = Buku.objects.all().order_by("jumlah_review")
    kata_bijak = quotes.objects.all()

    if "last_login" in request.COOKIES:
        if "last_login" in request.COOKIES:
            try:
                tingkatan = level.objects.get(user=request.user)
            except ObjectDoesNotExist:
                tingkatan = level(
                    user=request.user, level=0, buku_total=0, batas_atas=5, persen=0
                )
                tingkatan.save()

        context = {
            "persen": 100 * tingkatan.buku_total / tingkatan.batas_atas,
            "tingkatan": tingkatan,
            "kata_bijak": kata_bijak,
            "pengguna": request.user,
            "last_login": request.COOKIES["last_login"],
            "bukus": bukus,
            "karya": karya_pengguna,
        }
    else:
        context = {"kata_bijak": kata_bijak, "bukus": bukus, "karya": karya_pengguna}

    return render(request, "main.html", context)


@login_required(login_url="/login")
def create_buku(request):
    if request.method == "POST":
        form = BukuForm(request.POST, request.FILES)
        if form.is_valid():
            buku = form.save(commit=False)
            print(buku)
            buku.user = request.user
            buku.save()
            return HttpResponseRedirect(reverse("main:show_main"))

    else:
        form = BukuForm()

    context = {"form": form}
    return render(request, "create_buku.html", context)


def create_buku_baru(request):
    if request.method == "POST":
        print("\n Masuk bNag KE SAVE \n")
        form = BukuForm(request.POST, request.FILES)
        if form.is_valid():
            buku = form.save(commit=False)
            buku.user = request.user
            buku.save()
            return HttpResponseRedirect(
                reverse("main:autoSave", kwargs={"id_buku": buku.id})
            )

    else:
        form = BukuForm()

    context = {"form": form}
    return render(request, "create_buku_baru.html", context)


@csrf_exempt
def add_quotes_ajax(request):
    if request.method == "POST":
        kata = request.POST.get("quotes")
        user = request.user

        new_quotes = quotes(kata_kata=kata, user=user)
        new_quotes.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()


def filter_bintang_empat(request):
    karya_pengguna = (
        BukuKreasi.objects.all()
        .order_by("jumlah_review")
        .filter(is_published=True)
        .filter(rating__gt=4)
    )
    bukus = Buku.objects.all().order_by("jumlah_review").filter(rating__gt=4)

    if "last_login" in request.COOKIES:
        if hasattr(request, "level"):
            tingkatan = level.objects.get(user=request.user)
        context = {
            "persen": 100 * tingkatan.buku_total / tingkatan.batas_atas,
            "tingkatan": tingkatan,
            "pengguna": request.user,
            "last_login": request.COOKIES["last_login"],
            "bukus": bukus,
            "karya": karya_pengguna,
        }
    else:
        context = {"bukus": bukus, "karya": karya_pengguna}
    return render(request, "filterbintangempat.html", context)


def filter_bahasa_inggris(request):
    karya_pengguna = (
        BukuKreasi.objects.all()
        .order_by("jumlah_review")
        .filter(is_published=True)
        .filter(bahasa="eng")
    )
    bukus = Buku.objects.all().order_by("jumlah_review").filter(bahasa="eng")

    if "last_login" in request.COOKIES:
        if hasattr(request, "level"):
            tingkatan = level.objects.get(user=request.user)
        context = {
            "persen": 100 * tingkatan.buku_total / tingkatan.batas_atas,
            "tingkatan": tingkatan,
            "pengguna": request.user,
            "last_login": request.COOKIES["last_login"],
            "bukus": bukus,
            "karya": karya_pengguna,
        }
    else:
        context = {"bukus": bukus, "karya": karya_pengguna}
    return render(request, "filterbukuinggris.html", context)


def filter_buku_karya(request):
    karya_pengguna = (
        BukuKreasi.objects.all().order_by("jumlah_review").filter(is_published=True)
    )

    if "last_login" in request.COOKIES:
        if hasattr(request, "level"):
            tingkatan = level.objects.get(user=request.user)
        context = {
            "persen": 100 * tingkatan.buku_total / tingkatan.batas_atas,
            "tingkatan": tingkatan,
            "pengguna": request.user,
            "last_login": request.COOKIES["last_login"],
            "karya": karya_pengguna,
        }
    else:
        context = {"karya": karya_pengguna}
    return render(request, "filterbukuinggris.html", context)


@login_required(login_url="/login")
def show_my_quotes(request):
    kata_saya = quotes.objects.filter(user=request.user)

    context = {"kata_saya": kata_saya}

    return render(request, "katasaya.html", context)


def delete_quotes(request, id):
    katabijak = quotes.objects.get(pk=id)
    katabijak.delete()
    return HttpResponseRedirect(reverse("main:show_my_quotes"))


def show_xml(request):
    data = Buku.objects.all()
    return HttpResponse(
        serializers.serialize("xml", data), content_type="application/xml"
    )


def show_buku_json(request):
    data = Buku.objects.all()
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_buku_kreasi_json(request):
    data = BukuKreasi.objects.all()
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_quotes_json(request):
    data = BukuKreasi.objects.all()
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_profile_json(request):
    user = request.user
    data = profile.objects.filter(user=user)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_level_json(request):
    user = request.user
    data = level.objects.filter(user=user)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_my_quotes_json(request):
    user = request.user
    data = quotes.objects.filter(user=user)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_xml_by_id(request, id):
    data = Buku.objects.filter(pk=id)
    return HttpResponse(
        serializers.serialize("xml", data), content_type="application/xml"
    )


def show_json_by_id(request, id):
    data = Buku.objects.filter(pk=id)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your account has been successfully created!")
            return redirect("main:login")
    context = {"form": form}
    return render(request, "register.html", context)


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie("last_login", str(datetime.datetime.now()))
            return response
        else:
            messages.info(
                request, "Sorry, incorrect username or password. Please try again."
            )
    context = {}
    return render(request, "login.html", context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse("main:show_main"))
    response.delete_cookie("last_login")
    return response


def edit_buku(request, id):
    # Get buku berdasarkan ID
    buku = Buku.objects.get(pk=id)

    # Set buku sebagai instance dari form
    form = BukuForm(request.POST or None, instance=buku)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse("main:show_main"))

    context = {"form": form}

modul_create_book/templates/create_buku_baru.html
{% extends 'base.html' %} 

{% block content %}
<head>
    
    <link rel="stylesheet" href="/static/create_buku.css" "="">
    
    
    
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        {% comment %} <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script> {% endcomment %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    </head>
<body>

    

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">STORICA</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Buat Cerita</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " aria-disabled="false">Tulis Buku</a>
              </li>
              <li class="nav-item">
                <a class="nav-link " aria-disabled="false">Kelola Akun</a>
              </li>
            </ul>
             
              <button class="profile_icon" id="profile_icon">
                <img class="avatar" src="/static/images/man.png" alt="Profile_Icon">
            </button>
          </div>
        </div>
      </nav>
    
    
    
        
    
    <h1 class="judul_page">TAMBAH BUKU</h1>
    <div class="container">
    <div class="form">
        <form method="POST" class="book_form" enctype="multipart/form-data" id="form">
        {% csrf_token %}
            <br><table>
                <tbody><tr class="fields_container">
                    <td>
                        <label for="judul">Judul  </label>
                    </td>
                    <td class="fields">
                       <input  type="text" name="judul" maxlength="25" id="judul" oninput="showJudul()" >
                    </td>
                </tr>
        
                <tr class="fields_container">
                    <td>
                        <label for="jumlah_halaman">Jumlah Halaman  </label>
    
                    </td>
                    <td class="fields">
                        <input  type="number" name="jumlah_halaman" min="0" id="jumlah_halaman" class="jumlah_halaman">
                    </td>
                </tr>
                
                <tr class="fields_container">
                    <td>
                        <label for="bahasa">Bahasa  </label>
    
                    </td>
                    <td class="fields">
                        <input  type="text" name="bahasa" maxlength="50" id="bahasa">
                    </td>
                </tr>
    
                <tr class="fields_container">
                    <td>
                        <label for="penerbit">Penerbit  </label>
    
                    </td>
                    <td class="fields">
                        <input  type="text" name="penerbit" maxlength="25" id="penerbit">
                    </td>
                </tr>

                <tr class="fields_container">
                    <td>
                        <label for="penulis">Penulis</label>
    
                    </td>
                    <td class="fields">
                        <input  type="text" name="penulis" maxlength="25" id="penulis" oninput="showPenulis()">
                    </td>
                </tr>
    
                <tr class="fields_container">
                    <td>
                        <label for="tanggal_terbit">Tanggal Terbit  </label>
    
                    </td>
                    <td class="fields">
                        <input  type="date" name="tanggal_terbit" required="" id="tanggal_terbit" class="tanggal_terbit_fields">
                    </td>
                </tr>
    
                <tr class="fields_container">
                    <td>
                        <label for="sampul_buku">Sampul </label>
    
                    </td>
                    <td class="fields">
                        <input  type="file" accept="image/*" id="select-img" class="select-img"  onchange="showme()">
                        
                    </td>
                </tr>
    
    
            </tbody></table>
           
            <a href="{% url 'main:show_main' %}" class="back-btn">
              <button type="button" class="btn btn-success back-btn">Back</button>
            </a>
            <button class="btn btn-success next-btn"  type = "submit" onclick="valueChecking()"  >Next</button>
          </form>
    
            
        
        </div>


    
        <div class="priview">
    
                <img  alt="sampul" class="sampul" id ="sampul" style="display: none;">
                <p class="warning">1920 X 1080</p>
            <div class="book_properties">
                    <p class="judul_buku" id ="judul_buku_view">Judul Buku</p>
                    <p class="penulis" id="penulis_view">Penulis</p>
            </div>
       
    <!-- Vertically centered modal -->

        </div>

        
      </div>
      
      
      <div class="backpopup" id="backpopup" style="display: none;" >


        <div class="popup-frame">
          <h2 class="pilihan-buat-cerita">Silahkan Pilih Metode Pembuatan Cerita</h2>
            <div class="pilihan">
              <label type="file" class="pdf-btn" id="pdf-btn">
                  <img src="static/images/pdf.png" alt="" class="pdf-icon">
              </label>
              <a href="{% url 'main:create_isi_buku'  %}" class="livewriting-url">

                <button class="livewriting-btn">
                  <img src="static/images/writing.png" alt="" class="livewriting-icon" >
                </button>
              </a>
            </div>
        </div>

    </div>
      
    
    
    <script>
        function showme(){
            const fileinput = document.getElementById('select-img')
            const field_img = document.getElementById('sampul')

            var reader = new FileReader();
            image = fileinput.files[0]
            img_src= URL.createObjectURL(image)
            image.style.display="flex"
            reader.readAsDataURL(image);
            field_img.style.opacity = 1
            console.log(image)


            let WIDTH = 800
            let ratio = WIDTH/image.width
            let heigth = image.heigth * ratio
            console.log(image.width)
           // field_img.width = ratio
           // field_img.heigth  = heigth


            reader.addEventListener('load', ()=>{
              field_img.src=img_src;
            })


          }



          function showJudul(){
            const field_judul  = document.getElementById('judul_buku_view')
            const judul = document.getElementById('judul')
            console.log(judul.value)
            field_judul.innerHTML = judul.value
          }
          function showPenulis(){
            const field_penulis  = document.getElementById('penulis_view')
            const form = document.getElementById('form')

            const penulis = document.getElementById('penulis')
            console.log(penulis)
            field_penulis.innerHTML = penulis.value
          }

          function showpopup(){
            const popup = document.getElementById('backpopup')
            const elemenPopup = document.getElementById('pdf-btn')
            elemenPopup.innerHTML += '<input  type="file" style="display: none;" >'
            popup.style.display="flex"
          }

          async function saveForm(){
            await fetch(`{% url 'main:create_buku' %}`)

          }

    

          function valueChecking(){
            const inputs = document.querySelectorAll('input')
            var isNotEmpty = 0
            console.log( isNotEmpty)
            (inputs.forEach(function(elemen){
              if (elemen.value == ''){


                console.log("ini kosong : " + elemen.id )
              }else{
                console.log("ini : " + elemen.value )
                isNotEmpty+=(1);
                if(isNotEmpty == 8){
                  showpopup()
                }
                
              }
              console.log("hasikl : "+ isNotEmpty)
            
            }))


             
          }
          function isNotNull(){
            const inputs = document.querySelectorAll('input')
              if (inputs.value == undefined) {
                return false ;
              }
            return true


          }

         

    $(document).ready(function () {
        $('.datepicker').datepicker({
          format: 'yyyy-mm-dd',
          autoclose: true
        })
      
        $('.timepicker').timepicker({
          format: 'hh:ii:ss',
          autoclose: true,
          showMeridian: false
        })
      
        $('.datetimepicker').datetimepicker({
          format: 'YYYY-MM-DD HH:mm:ss',
          showClear: true
        })
      })


      
    </script>
    
    
    
    
    
    
    
    
    
    </body>

{% endblock %}

modul_create_book/templates/edit_buku.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<h1>Edit Buku</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Buku"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

modul_create_book/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>

</div>

{% endblock content %}

modul_create_book/templates/main.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="my-4">Storica</h1>

    <div class="row">
        {% for buku in bukus %}
        <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-4">
            <div class="card">
                <img src="{{ buku.gambar }}" alt="{{ buku.judul }}" class="card-img-top">
                <div class="card-body">
                    <h5 class="card-title">{{ buku.judul }}</h5>
                    <p class="card-text">Author: {{ buku.penulis }}</p>
                    <p class="card-text">Pages: {{ buku.jumlah_halaman }}</p>
                    <p class="card-text">Language: {{ buku.bahasa }}</p>
                    <p class="card-text">Publisher: {{ buku.penerbit }}</p>
                    <p class="card-text">Rating: {{ buku.rating }}</p>
                    <p class="card-text">Publish Date: {{ buku.tanggal_terbit }}</p>
                </div>
                <a href="{% url 'main:edit_buku' buku.pk %}">
                    <button>
                        Edit
                    </button>
                </a>
                <a href="{% url 'main:delete_buku' buku.pk %}">
                    <button>
                        Delete
                    </button>
                </a>
            </div>
        </div>
        {% if forloop.counter|divisibleby:5 and not forloop.last %}
    </div>
    <div class="row">
        {% endif %}
        {% endfor %}
    </div>

    <br />
    <h5 class="my-4">Sesi terakhir login: {{ last_login }}</h5>

    <a href="{% url 'main:create_buku' %}">
        <button class="btn btn-primary">Add New Buku</button>
    </a>

    <a href="{% url 'main:logout' %}">
        <button class="btn btn-danger">Logout</button>
    </a>
</div>
{% endblock content %}

modul_create_book/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Register</h1>  

        <form method="POST" enctype="multipart/form-data">  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}