main/urls.py
from django.urls import path
from main.views import *
from main.views import add_quotes_ajax
from . import views

app_name = 'main'

urlpatterns = [
    path('create-quotes-ajax/',add_quotes_ajax,name="add_quotes_ajax"),
    path('filter-inggris/',filter_bahasa_inggris,name='filter_inggris'),
    path('filter-karya/',filter_buku_karya,name='filter_karya'),
    path('filter-empat/',filter_bintang_empat,name='filter_empat'),
    path('my-quotes/',show_my_quotes,name='show_my_quotes'),
    path('koleksi-buku/',show_semua, name ='show_semua'),
    path('login', login_user, name='login'),
    path('', show_main, name='show_main'),
    path('create-buku', create_buku, name='create_buku'),
    path('xml/', show_xml, name='show_xml'), 
    path('buku-json/', show_buku_json, name='show_buku_json'),
    path('bukukreasi-json/', show_buku_kreasi_json, name='show_bukukreasi_json'),
    path('myquotes-json/', show_my_quotes_json, name='show_myquotes_json'),
    path('profile-json/', show_profile_json, name='show_profile_json'), 
    path('quotes-json/', show_quotes_json, name='show_quotes_json'),
    path('level-json/', show_level_json, name='show_level_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('edit-buku/<int:id>', edit_buku, name='edit_buku'),
    path('delete/<int:id>', delete_buku, name='delete_buku'),
    path('preview/<int:id>', show_preview, name='show_preview'),
    path('preview-kreasi/<int:id>', show_preview_kreasi, name='show_preview_kreasi'),
    path('get-quotes-jason',get_quotes_json,name="get_quotes_json"),
    path('delete-quotes/<int:id>', delete_quotes, name='delete_quotes'),
    path("create-isi-buku", views.createIsiBuku, name="create_isi_buku"),
    path("create-isi-buku-baru", views.createIsiBuku, name="create_isi_buku_baru"),
    path("publish/<int:id_buku>", views.publish, name="publish"),
    path("create-isi-buku-saved/<int:id_buku>", views.autoSave, name="autoSave"),
    path("create-buku-baru", views.create_buku_baru, name='create_buku_baru'),
]

modul_favorites/urls.py
from django.urls import path
from modul_favorites.views import *

app_name = 'modul_favorites'

urlpatterns = [
    path('show_favorites/', show_favorites, name='show_favorites'),
    path('add_favorites/<int:id>', add_favorites, name='add_favorites'),
    path('remove_favorites/<int:id>', remove_favorites, name='remove_favorites'),
]

storica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('preview/', include('modul_preview.urls')),
    path('preview/baca/', include('modul_baca.urls')),
    path('favorites/', include('modul_favorites.urls')),
    path('create-buku/create-buku', include('modul_create_book.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block meta %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock meta %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}" />
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'main:show_main'%}"><strong>STORICA</strong></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown"> 
            <ul class="navbar-nav" style="flex: auto;">
                <li class="nav-item">
                    <ul class="nav"> {# Add the nav class to create horizontal links #}
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url 'main:logout' %}" class="nav-link">Logout</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'modul_favorites:show_favorites' %}" class="nav-link">Favorites</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'main:create_buku' %}">Buat Cerita</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a href="{% url 'main:login' %}" class="nav-link">Login</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'main:register' %}" class="nav-link">Register</a>
                        </li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
          </div>
          
          <p style="color:black;font-size:18px;" align="right"><strong>User: {{request.user.username}}</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
</body>

</html>

templates/base_exclude.html
{% load static %}
<!DOCTYPE html>
<html lang="en">



<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'main:show_main'%}"><strong>STORICA</strong></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item">
                {% if request.user.is_authenticated %}
                <a href="{% url 'main:logout' %}">
                    <button  style= "color: rgb(255, 255, 255);margin-bottom: 5px;background-color: rgb(50, 59, 218);width: 100%; border-radius: 8px;border: none;height: 35px;">
                        Logout
                    </button>
                </a>
                <a href="{% url 'modul_favorites:show_favorites' %}">
                    <button  style= "color: rgb(255, 255, 255);margin-bottom: 5px;background-color: rgb(50, 59, 218);width: 100%; border-radius: 8px;border: none;height: 35px;">
                        Favorites
                    </button>
                </a>
                {% else %}
                <a href="{% url 'main:register' %}">
                    <button  style= "color: rgb(255, 255, 255);margin-bottom: 5px;background-color: rgb(50, 59, 218);width: 100%; border-radius: 8px;border: none;height: 35px;">
                        Register
                    </button>
                </a>
                <a href="{% url 'main:login' %}">
                    <button  style= "color: rgb(255, 255, 255);margin-bottom: 5px;background-color: rgb(50, 59, 218);width: 100%; border-radius: 8px;border: none;height: 35px;">
                        Login
                    </button>
                </a>
                {% endif %}
              </li>
            </ul>
          </div>
          <p style="color:black;font-size:18px;" align="right"><strong>User: {{request.user.username}}</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
</body>

</html>

templates/header.html
{% extends "templates/base.html" %}