main/urls.py
from django.urls import path
from main.views import *
from main.views import add_quotes_ajax
from . import views

app_name = 'main'

urlpatterns = [
    path('create-quotes-ajax/',add_quotes_ajax,name="add_quotes_ajax"),
    path('filter-inggris/',filter_bahasa_inggris,name='filter_inggris'),
    path('filter-karya/',filter_buku_karya,name='filter_karya'),
    path('filter-empat/',filter_bintang_empat,name='filter_empat'),
    path('my-quotes/',show_my_quotes,name='show_my_quotes'),
    path('koleksi-buku/',show_semua, name ='show_semua'),
    path('login', login_user, name='login'),
    path('', show_main, name='show_main'),
    path('create-buku', create_buku, name='create_buku'),
    path('xml/', show_xml, name='show_xml'), 
    path('buku-json/', show_buku_json, name='show_buku_json'),
    path('bukukreasi-json/', show_buku_kreasi_json, name='show_bukukreasi_json'),
    path('myquotes-json/', show_my_quotes_json, name='show_myquotes_json'),
    path('profile-json/', show_profile_json, name='show_profile_json'), 
    path('quotes-json/', show_quotes_json, name='show_quotes_json'),
    path('level-json/', show_level_json, name='show_level_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('edit-buku/<int:id>', edit_buku, name='edit_buku'),
    path('delete/<int:id>', delete_buku, name='delete_buku'),
    path('preview/<int:id>', show_preview, name='show_preview'),
    path('preview-kreasi/<int:id>', show_preview_kreasi, name='show_preview_kreasi'),
    path('get-quotes-jason',get_quotes_json,name="get_quotes_json"),
    path('delete-quotes/<int:id>', delete_quotes, name='delete_quotes'),
    path("create-isi-buku", views.createIsiBuku, name="create_isi_buku"),
    path("create-isi-buku-baru", views.createIsiBuku, name="create_isi_buku_baru"),
    path("publish/<int:id_buku>", views.publish, name="publish"),
    path("create-isi-buku-saved/<int:id_buku>", views.autoSave, name="autoSave"),
    path("create-buku-baru", views.create_buku_baru, name='create_buku_baru'),
]

storica/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('preview/', include('modul_preview.urls')),
    path('preview/baca/', include('modul_baca.urls')),
    path('favorites/', include('modul_favorites.urls')),
    path('create-buku/create-buku', include('modul_create_book.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Buku(models.Model):
    judul = models.CharField(max_length=255, null=True, blank=True)
    jumlah_halaman = models.PositiveIntegerField(null=True, blank=True)
    bahasa = models.CharField(max_length=50, null=True, blank=True)
    penulis = models.CharField(max_length=255, null=True, blank=True)
    penerbit = models.CharField(max_length=255, null=True, blank=True)
    jumlah_review = models.PositiveIntegerField(null=True, blank=True)
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    gambar = models.URLField(null=True, blank=True)
    tanggal_terbit = models.DateField(null=True, blank=True)
    buku_favorites = models.ManyToManyField(User)
    isi_buku = models.TextField(default="Sayangnya buku ini belum tersedia :(, silahkan coba buku lainnya")


class BukuKreasi(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True,blank=True)
    judul = models.CharField(max_length=255, null=True, blank=True)
    jumlah_halaman = models.PositiveIntegerField(null=True, blank=True)
    bahasa = models.CharField(max_length=50, null=True, blank=True)
    penulis = models.CharField(max_length=255, null=True, blank=True)
    penerbit = models.CharField(max_length=255, null=True, blank=True)
    jumlah_review = models.PositiveIntegerField(null=True, blank=True)
    rating = models.DecimalField(max_digits=3, decimal_places=2, null=True, blank=True)
    gambar = models.URLField(null=True, blank=True)
    tanggal_terbit = models.DateField(null=True, blank=True)
    is_published = models.BooleanField()
    isi_buku = models.TextField(null="",blank="")


    # Representasi teks model 
    def __str__(self):
        return self.judul

class level(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    level = models.PositiveIntegerField()
    buku_total = models.PositiveIntegerField()
    batas_atas = models.PositiveIntegerField()
    persen = models.PositiveIntegerField()


class quotes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    kata_kata = models.TextField()

class profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    gambar = models.URLField(null=True, blank=True)

main/forms.py
from django.forms import ModelForm
from main.models import BukuKreasi

class BukuForm(ModelForm):
    class Meta:
        model = BukuKreasi
        fields = ["judul", "jumlah_halaman", "bahasa", "penulis", "penerbit", "jumlah_review", "rating", "gambar", "tanggal_terbit", "isi_buku", "is_published"]

main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from main.models import *
from main.forms import BukuForm
from django.urls import reverse
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from django.core.files.storage import FileSystemStorage
from django.core.exceptions import ObjectDoesNotExist


def get_buku_json(request):
    buku = Buku.objects.all().order_by("jumlah_review")
    return HttpResponse(serializers.serialize("json", buku))


def get_bukukreasi_json(request):
    bukukreasi = Buku.objects.all().order_by("jumlah_review")
    return HttpResponse(serializers.serialize("json", bukukreasi))


def show_semua(request):
    karya_pengguna = (
        BukuKreasi.objects.all().order_by("jumlah_review").filter(is_published=True)
    )
    bukus = Buku.objects.all().order_by("jumlah_review")

    context = {"bukus": bukus, "karya": karya_pengguna}
    return render(request, "semuabuku.html", context)


def show_main(request):
    karya_pengguna = (
        BukuKreasi.objects.all().order_by("jumlah_review").filter(is_published=True)
    )
    bukus = Buku.objects.all().order_by("jumlah_review")
    kata_bijak = quotes.objects.all()

    if "last_login" in request.COOKIES:
        if "last_login" in request.COOKIES:
            try:
                tingkatan = level.objects.get(user=request.user)
            except ObjectDoesNotExist:
                tingkatan = level(
                    user=request.user, level=0, buku_total=0, batas_atas=5, persen=0
                )
                tingkatan.save()

        context = {
            "persen": 100 * tingkatan.buku_total / tingkatan.batas_atas,
            "tingkatan": tingkatan,
            "kata_bijak": kata_bijak,
            "pengguna": request.user,
            "last_login": request.COOKIES["last_login"],
            "bukus": bukus,
            "karya": karya_pengguna,
        }
    else:
        context = {"kata_bijak": kata_bijak, "bukus": bukus, "karya": karya_pengguna}

    return render(request, "main.html", context)


@login_required(login_url="/login")
def create_buku(request):
    if request.method == "POST":
        form = BukuForm(request.POST, request.FILES)
        if form.is_valid():
            buku = form.save(commit=False)
            print(buku)
            buku.user = request.user
            buku.save()
            return HttpResponseRedirect(reverse("main:show_main"))

    else:
        form = BukuForm()

    context = {"form": form}
    return render(request, "create_buku.html", context)


def create_buku_baru(request):
    if request.method == "POST":
        print("\n Masuk bNag KE SAVE \n")
        form = BukuForm(request.POST, request.FILES)
        if form.is_valid():
            buku = form.save(commit=False)
            buku.user = request.user
            buku.save()
            return HttpResponseRedirect(
                reverse("main:autoSave", kwargs={"id_buku": buku.id})
            )

    else:
        form = BukuForm()

    context = {"form": form}
    return render(request, "create_buku_baru.html", context)


@csrf_exempt
def add_quotes_ajax(request):
    if request.method == "POST":
        kata = request.POST.get("quotes")
        user = request.user

        new_quotes = quotes(kata_kata=kata, user=user)
        new_quotes.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()


def filter_bintang_empat(request):
    karya_pengguna = (
        BukuKreasi.objects.all()
        .order_by("jumlah_review")
        .filter(is_published=True)
        .filter(rating__gt=4)
    )
    bukus = Buku.objects.all().order_by("jumlah_review").filter(rating__gt=4)

    if "last_login" in request.COOKIES:
        if hasattr(request, "level"):
            tingkatan = level.objects.get(user=request.user)
        context = {
            "persen": 100 * tingkatan.buku_total / tingkatan.batas_atas,
            "tingkatan": tingkatan,
            "pengguna": request.user,
            "last_login": request.COOKIES["last_login"],
            "bukus": bukus,
            "karya": karya_pengguna,
        }
    else:
        context = {"bukus": bukus, "karya": karya_pengguna}
    return render(request, "filterbintangempat.html", context)


def filter_bahasa_inggris(request):
    karya_pengguna = (
        BukuKreasi.objects.all()
        .order_by("jumlah_review")
        .filter(is_published=True)
        .filter(bahasa="eng")
    )
    bukus = Buku.objects.all().order_by("jumlah_review").filter(bahasa="eng")

    if "last_login" in request.COOKIES:
        if hasattr(request, "level"):
            tingkatan = level.objects.get(user=request.user)
        context = {
            "persen": 100 * tingkatan.buku_total / tingkatan.batas_atas,
            "tingkatan": tingkatan,
            "pengguna": request.user,
            "last_login": request.COOKIES["last_login"],
            "bukus": bukus,
            "karya": karya_pengguna,
        }
    else:
        context = {"bukus": bukus, "karya": karya_pengguna}
    return render(request, "filterbukuinggris.html", context)


def filter_buku_karya(request):
    karya_pengguna = (
        BukuKreasi.objects.all().order_by("jumlah_review").filter(is_published=True)
    )

    if "last_login" in request.COOKIES:
        if hasattr(request, "level"):
            tingkatan = level.objects.get(user=request.user)
        context = {
            "persen": 100 * tingkatan.buku_total / tingkatan.batas_atas,
            "tingkatan": tingkatan,
            "pengguna": request.user,
            "last_login": request.COOKIES["last_login"],
            "karya": karya_pengguna,
        }
    else:
        context = {"karya": karya_pengguna}
    return render(request, "filterbukuinggris.html", context)


@login_required(login_url="/login")
def show_my_quotes(request):
    kata_saya = quotes.objects.filter(user=request.user)

    context = {"kata_saya": kata_saya}

    return render(request, "katasaya.html", context)


def delete_quotes(request, id):
    katabijak = quotes.objects.get(pk=id)
    katabijak.delete()
    return HttpResponseRedirect(reverse("main:show_my_quotes"))


def show_xml(request):
    data = Buku.objects.all()
    return HttpResponse(
        serializers.serialize("xml", data), content_type="application/xml"
    )


def show_buku_json(request):
    data = Buku.objects.all()
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_buku_kreasi_json(request):
    data = BukuKreasi.objects.all()
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_quotes_json(request):
    data = BukuKreasi.objects.all()
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_profile_json(request):
    user = request.user
    data = profile.objects.filter(user=user)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_level_json(request):
    user = request.user
    data = level.objects.filter(user=user)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_my_quotes_json(request):
    user = request.user
    data = quotes.objects.filter(user=user)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def show_xml_by_id(request, id):
    data = Buku.objects.filter(pk=id)
    return HttpResponse(
        serializers.serialize("xml", data), content_type="application/xml"
    )


def show_json_by_id(request, id):
    data = Buku.objects.filter(pk=id)
    return HttpResponse(
        serializers.serialize("json", data), content_type="application/json"
    )


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your account has been successfully created!")
            return redirect("main:login")
    context = {"form": form}
    return render(request, "register.html", context)


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie("last_login", str(datetime.datetime.now()))
            return response
        else:
            messages.info(
                request, "Sorry, incorrect username or password. Please try again."
            )
    context = {}
    return render(request, "login.html", context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse("main:show_main"))
    response.delete_cookie("last_login")
    return response


def edit_buku(request, id):
    # Get buku berdasarkan ID
    buku = Buku.objects.get(pk=id)

    # Set buku sebagai instance dari form
    form = BukuForm(request.POST or None, instance=buku)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse("main:show_main"))

    context = {"form": form}

main/templates/create_buku.html
{% extends 'base.html' %} 

{% block content %}
<h1>Add New Buku</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Buku"/>
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/filterbintangempat.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'main/css/semuabuku.css' %}" />
{% endblock meta %}

{% block content %}

<div class="container" style="margin-top: 5px;">
    <div class="row">
        <h4><strong>Hasil Pencarian</strong></h4>
    </div>
    <br/><br/>
    <div class="row gy-5">
        {% for karya in karya %}
            <div class="col-2">
                <div class="card" id="sampulkecil">
                    <a href ="{% url 'main:show_preview' karya.pk %}">
                        <button class="buttonbukukecil">                                    
                            <img src="{{karya.gambar}}" id="sampulbuku" alt="...">
                            <div class="penampungjudul">
                                <ul class="smallfont">
                                    <li id = "coverkecil"><Strong id = "coverkecil">{{karya.judul}}</Strong></li>
                                    <li id = "coverkecil">{{karya.penulis}}</li>
                                </ul>  
                            </div>
                        </button>                                
                    </a>
                </div>
            </div>
        {% endfor %}
        {% for buku in bukus %}
            <div class="col-2">
                <div class="card" id="sampulkecil">
                    <a href ="{% url 'main:show_preview' buku.pk %}">
                        <button class="buttonbukukecil">                                    
                            <img src="{{buku.gambar}}" id="sampulbuku" alt="...">
                            <div class="penampungjudul">
                                <ul class="smallfont">
                                    <li id = "coverkecil"><Strong id = "coverkecil">{{buku.judul}}</Strong></li>
                                    <li id = "coverkecil">{{buku.penulis}}</li>
                                </ul>  
                            </div>
                        </button>                                
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div id ="kembalilagi">
    <a style="align-self: center;"href = "{% url 'main:show_semua' %}">
        <button  class="tombolkembali">Kembali</button>
    </a>
    </div>
</div>        
    <script type="text/JavaScript" src="{% static 'main/js/semuabuku.js' %}"></script>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'main/css/semuabuku.css' %}" />
{% endblock meta %}


{% block content %}

<div class="container" style="margin-top:0px;margin-bottom:0px">
    <div class = "row">
        <div class = "col-4" style="padding-right:0">
            <h4><strong>Karya Pengguna</strong></h4>
            <div id = "carouselindicator" class = "carousel slide" data-bs-ride="true">
                <div class="carousel-indicators">
                    {% for karya in karya %}
                        {% if forloop.counter0 < 5 %}
                            {% if forloop.counter0 == 0 %}
                                <button id="indikatorlingkaran" type="button" data-bs-target="#carouselindicator" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                            {% else %}
                                <button id="indikatorlingkaran" type="button" data-bs-target="#carouselindicator" data-bs-slide-to="{{forloop.counter0}}" aria-current="true" aria-label="Slide {{forloop.counter}}"></button>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
                
                <div class="carousel-inner">
                    {% for karya in karya %}
                        {% if forloop.counter0 < 5 %}
                            {% if forloop.counter0 == 0 %}
                                
                                <div class="carousel-item active">
                                    <a href = "{% url 'main:show_preview_kreasi' karya.pk %}">
                                    <button class="buttonbuku">
                                        <img src="{{karya.gambar}}" id="sampulbuku" alt="...">
                                        <div class="penampungjudul">
                                            <ul>
                                                <li id = "cover"><Strong id = "cover">{{karya.judul}}</Strong></li>
                                                <li id = "cover">{{karya.penulis}}</li>
                                            </ul>  
                                        </div>
                                    </button>
                                    </a>
                                </div>
                            {% else %}
                                <div class="carousel-item">
                                    <a href = "{% url 'main:show_preview_kreasi' karya.pk %}">
                                    <button class="buttonbuku">
                                        <img src="{{karya.gambar}}" id="sampulbuku" alt="...">
                                        <div class="penampungjudul">
                                            <ul>
                                                <li id = "cover"><Strong id = "cover">{{karya.judul}}</Strong></li>
                                                <li id = "cover">{{karya.penulis}}</li>
                                            </ul>                                            
                                        </div>
                                    </button>
                                    </a>
                                </div>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>

                <div>
                    {% for karya in karya %}
                        {% if forloop.counter0 < 5 %}
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselindicator" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                          </button>
                          <button class="carousel-control-next" type="button" data-bs-target="#carouselindicator" data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                          </button>
                        {% endif %}
                    {% endfor %}
                </div>   
            </div>
        </div>
        <div class = "col-8" style="padding-right: 70px;padding-left: 90px;">
            <div>
                <h5><strong>Koleksi Buku</strong><br/><br/></h5>
            </div>
            <div class = "row gx-5" id = "untukbuku">
                {% for buku in bukus %}
                    {% if forloop.counter0 < 4 %}
                        <div class="col-3">
                            <div class="card" id="sampulkecil">
                                <a href ="{% url 'main:show_preview' buku.pk %}">
                                    <button class="buttonbukukecil">                                    
                                        <img src="{{buku.gambar}}" id="sampulbuku" alt="...">
                                        <div class="penampungjudul">
                                            <ul class="smallfont">
                                                <li id = "coverkecil"><Strong id = "coverkecil">{{buku.judul}}</Strong></li>
                                                <li id = "coverkecil">{{buku.penulis}}</li>
                                            </ul>  
                                        </div>
                                    </button>                                
                                </a>
                            </div>
                        </div>
                    {%endif %}
                {% endfor %}
                <div class = "row" style="padding-top:15px;padding-right:  0px; margin-right: 0px;">
                    <a href = "{% url 'main:show_semua' %}" align=right style="padding:0px;">
                        <button  align=right style="background-color: #240000;border-radius: 20px;color:whitesmoke">Lihat Semua</button>
                    </a>
                </div>
            </div>
            <div class = "row" id = "untukkatabijak" >
                <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel" style="height: 30vh;max-height: 30vh;">                    
                    <div id="akandiajax" class="carousel-inner" style="max-height: 30vh;height: 30vh;">
                        {% for kata in kata_bijak %}
                            {% if forloop.counter0 == 0 %}
                                <div class="carousel-item active" style="max-height: 30vh;height: 30vh;">
                                    <p style="overflow-y: auto;">{{kata.kata_kata}}</p>
                                    <p>~{{kata.pengguna}}</p>
                                </div>
                            {% else %}
                                <div class="carousel-item" style="max-height: 30vh;height: 30vh;">
                                    <p style="overflow-y: scroll;">{{kata.kata_kata}}</p>
                                    <p>~{{kata.pengguna}}</p>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <div class="col-4" align ="right">
                <a href="{% url 'main:show_my_quotes' %}"  align=right>
                    <button align = right style="height: 30px; width: 200px; border-radius: 20px;background-color: #240000;color: whitesmoke;">Quotes Saya</button>
                </a>
                </div>
                <div class="col-4">
                    {% if user.is_authenticated %}
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="height: 30px; width: 200px; border-radius: 20px;background-color: #240000;color: whitesmoke;border: none;">Buat Quotes</button>
                    {% else %}
                    <a href="{% url 'main:login' %}"  align=right>
                        <button align = right style="height: 30px; width: 200px; border-radius: 20px;background-color: #240000;color: whitesmoke;">Buat Quotes</button>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="quotes" class="col-form-label">Quotes Anda:</label>
                        <textarea class="form-control" id="quotes" name="quotes"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Tutup</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Buat quotes</button>
            </div>
        </div>
    </div>
</div>
<input type="hidden" id="Url" data-url="{% url 'main:add_quotes_ajax' %}" />
<input type="hidden" id="Urlpalsu" data-url="{% url 'main:get_quotes_json' %}" />
<script type="text/JavaScript" src="{% static 'main/js/main.js' %}">
</script>
{% endblock content %}

main/templates/semuabuku.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'main/css/semuabuku.css' %}" />
{% endblock meta %}

{% block content %}
<div class="container" style="margin-top: 5px;">
    <h4><strong>Cari Buku: </strong></h4>
    <div class="row bx-5">
    <div class="col-2">
        <a href="{% url 'main:filter_empat' %}">
        <button style = "text-align:left;background-color:#24000000;color:  rgb(24,0,0);width: 150px;height: 30px;border-radius: 20px;border-color: #240000;"type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Rating (>4)</button>
        </a>
    </div>
    <div class="col-2">
        <a href="{% url 'main:filter_inggris' %}">
        <button style = "text-align:left;background-color:#24000000;color:  rgb(24,0,0);width: 150px;height: 30px;border-radius: 20px;border-color: #240000;"type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Bahasa (Inggris)</button>
        </a>
    </div>
    <div class="col-2">
        <a href="{% url 'main:filter_karya' %}">
        <button style = "text-align:left;background-color:#24000000;color:  rgb(24,0,0);width: 150px;height: 30px;border-radius: 20px;border-color: #240000;"type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Karya Pengguna</button>
        </a>
    </div>
</div>
    <br/><br/>
    <div class="row gy-5">
        {% for karya in karya %}
            <div class="col-2">
                <div class="card" id="sampulkecil">
                    <a href ="{% url 'main:show_preview' karya.pk %}">
                        <button class="buttonbukukecil">                                    
                            <img src="{{karya.gambar}}" id="sampulbuku" alt="...">
                            <div class="penampungjudul">
                                <ul class="smallfont">
                                    <li id = "coverkecil"><Strong id = "coverkecil">{{karya.judul}}</Strong></li>
                                    <li id = "coverkecil">{{karya.penulis}}</li>
                                </ul>  
                            </div>
                        </button>                                
                    </a>
                </div>
            </div>
        {% endfor %}
        {% for buku in bukus %}
            <div class="col-2">
                <div class="card" id="sampulkecil">
                    <a href ="{% url 'main:show_preview' buku.pk %}">
                        <button class="buttonbukukecil">                                    
                            <img src="{{buku.gambar}}" id="sampulbuku" alt="...">
                            <div class="penampungjudul">
                                <ul class="smallfont">
                                    <li id = "coverkecil"><Strong id = "coverkecil">{{buku.judul}}</Strong></li>
                                    <li id = "coverkecil">{{buku.penulis}}</li>
                                </ul>  
                            </div>
                        </button>                                
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div id ="kembalilagi">
    <a style="align-self: center;"href = "{% url 'main:show_main' %}">
        <button  class="tombolkembali">Kembali</button>
    </a>
    </div>
</div>        
    <script type="text/JavaScript" src="{% static 'main/js/semuabuku.js' %}"></script>
{% endblock content %}